[package]
name = "gitex"
version = "0.1.0"
authors = ["yagince <straitwalk@gmail.com>"]
edition = "2018"

[dependencies]
tui = "=0.9.1"
termion = "=1.5.5"
anyhow = "=1.0.28"
unicode-width = "=0.1.7"
git2 = "=0.13.5"