[package]
name = "gitex"
version = "0.1.0"
authors = ["yagince <straitwalk@gmail.com>"]
edition = "2018"

[dependencies]
tui = "0.9"
termion = "1.5"
anyhow = "1.0"
unicode-width = "0.1"
git2 = "0.13"
ansi_term = "0.12"